### ISSUE TITLE
User Story 51, Enabled Merchant Item's are active

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#12]
```
As an admin
When I visit the merchant index page
And I click on the "enable" button for a disabled merchant
Then all of that merchant's items should be activated
```

DO THESE STORIES FIRST:
- User Story 44, Admin Merchant Index Page

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #22

child of #70

depends on #19

**Comment by MackHalliday** [comment]
Final check OK
