### ISSUE TITLE
User Story 50, Admin enables a merchant account

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#13]
```
As an admin merchant
When I visit the merchant index page
I see an "enable" button next to any merchants whose accounts are disabled
When I click on the "enable" button
I am returned to the admin's merchant index page where I see that the merchant's account is now enabled
And I see a flash message that the merchant's account is now enabled
```

DO THESE STORIES FIRST:
- User Story 44, Admin Merchant Index Page

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #22

child of #70

depends on #19

**Comment by MackHalliday** [comment]
Finall check OK
