### ISSUE TITLE
User Story 48, Admin disables a merchant account

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#15]
```
As an admin
When I visit the merchant index page
I see a "disable" button next to any merchants who are not yet disabled
When I click on the "disable" button
I am returned to the admin's merchant index page where I see that the merchant's account is now disabled
And I see a flash message that the merchant's account is now disabled
```

DO THESE STORIES FIRST:
- User Story 44, Admin Merchant Index Page

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #22

child of #70

depends on #19

**Comment by MackHalliday** [comment]
Final check OK
