### ISSUE TITLE
User Story 47, Admin can see a merchant's dashboard

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#16]
```
As an admin user
When I visit the merchant index page ("/merchants")
And I click on a merchant's name,
I should be taken to my admin merchant show page ("/admin/merchants/6")
Then I see everything that merchant would see on their merchant dashboard page
```

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #22

child of #70

**Comment by MackHalliday** [comment]
Remove link from admin merchant show page

**Comment by MackHalliday** [comment]
Final Check OK
