### ISSUE TITLE
User Story 46, Admin User Profile Page

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#17]
```
As an admin user
When I visit a user's profile page ("/admin/users/5")
I see the same information the user would see themselves
I do not see a link to edit their profile
```

DO THESE STORIES FIRST:
- User Story 8, Admin Navigation
- User Story 45, Admin User Index Page

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #22

child of #70

depends on #60

depends on #18

**Comment by MackHalliday** [comment]
Final check OK
