### ISSUE TITLE
User Story 42, Admin can see all orders

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#21]
```
As an admin user
When I visit my admin dashboard ("/admin")
Then I see all orders in the system.
For each order I see the following information:

- user who placed the order, which links to admin view of user profile
- order id
- date the order was created

Orders are sorted by "status" in this order:

- packaged
- pending
- shipped
- cancelled
```

DO THESE STORIES FIRST:
- User Story 46, Admin User Profile Page

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #22

child of #70

depends on #17

**Comment by MackHalliday** [comment]
Final check OK
