### ISSUE TITLE
User Story 39, Merchant cannot add an item if details are bad/missing

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#25]
```
As a merchant admin
When I try to add a new item
If any of my data is incorrect or missing (except image)
Then I am returned to the form
I see one or more flash messages indicating each error I caused
All fields are re-populated with my previous data
```

DO THESE STORIES FIRST:
- User Story 38, Merchant adds an item

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #30

child of #70

depends on #26

**Comment by MackHalliday** [comment]
Final check OK
