### ISSUE TITLE
User Story 31, Merchant's Items index page

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#34]
```
As a merchant employee or admin
When I visit my merchant dashboard
I see a link to view my own items
When I click that link
I should be taken to my merchant's items ("/merchant/items")
```

DO THESE STORIES FIRST:
- User Story 18, User Profile Show Page

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #37

child of #70

depends on #48

**Comment by MackHalliday** [comment]
Final check ok
