### ISSUE TITLE
User Story 26, User views an Order Show Page

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#40]
```
As a registered user
When I visit my Profile Orders page
And I click on a link for order's show page
My URL route is now something like "/profile/orders/15"
I see all information about the order, including the following information:
- the ID of the order
- the date the order was made
- the date the order was last updated
- the current status of the order
- each item I ordered, including name, description, thumbnail, quantity, price and subtotal
- the total quantity of items in the whole order
- the grand total of all items for that order
```

DO THESE STORIES FIRST:
- User Story 25, User Profile displays Orders

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #50

child of #70

depends on #41

**Comment by MackHalliday** [comment]
Routes need to change so routes start with /profile
Example: /profile/orders/12

**Comment by MackHalliday** [comment]
Fix table headers on user order show page for shipping.

**Comment by MackHalliday** [comment]
Move logic from view to model/controller

**Comment by MackHalliday** [comment]
Final check OK
