### ISSUE TITLE
User Story 17, Items Index Page

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#49]
```
As a regular user
When I visit the items catalog ("/items")
Then I see all items in the system except disabled items

The item image is a link to that item's show page
```

DO THESE STORIES FIRST:
- User Story 5, Visitor Navigation

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #50

child of #70

depends on #63

**Comment by MackHalliday** [comment]
Final check OK
