### ISSUE TITLE
User Story 9, Visitor Navigation Restrictions

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#59]
```
As a Visitor
When I try to access any path that begins with the following, then I see a 404 error:
- '/merchant'
- '/admin'
- '/profile'
```

DO THESE STORIES FIRST:
- User Story 5, Visitor Navigation
- User Story 6, User Navigation
- User Story 7, Merchant Navigation
- User Story 8, Admin Navigation

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #64

child of #70

depends on #63

depends on #62

depends on #61

depends on #60

**Comment by MackHalliday** [comment]
Final check OK
