### ISSUE TITLE
User Story 8, Admin Navigation

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#60]
```
As an admin user
I see the same links as a regular user
Plus the following links
- a link to my admin dashboard ("/admin")
- a link to see all users ("/admin/users")

Minus the following links/info
- a link to my shopping cart ("/cart") or count of cart items
```

DO THESE STORIES FIRST:
- User Story 6, User Navigation

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #64

child of #70

depends on #62

**Comment by MackHalliday** [comment]
Final check OK 
Admin Users OK
