### ISSUE TITLE
User Story 7, Merchant Navigation

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#61]
```
As a merchant employee or admin
I see the same links as a regular user
Plus the following links:
- a link to my merchant dashboard ("/merchant")
```

DO THESE STORIES FIRST:
- User Story 6, User Navigation

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #64

child of #70

depends on #62

**Comment by MackHalliday** [comment]
Final check OK 
Merchant Admin OK 
Merchant Employee OK
