### ISSUE TITLE
User Story 6, User Navigation

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#62]
```
As a registered regular user
I see the same links as a visitor
Plus the following links
- a link to my profile page ("/profile")
- a link to log out ("/logout")

Minus the following links
- I do not see a link to log in or register

I also see text that says "Logged in as Ian Douglas" (or whatever my name is)
```

DO THESE STORIES FIRST:
- User Story 5, Visitor Navigation

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #64

child of #70

depends on #63

**Comment by MackHalliday** [comment]
Final check OK
