### ISSUE TITLE
User Story 4, Registration Email must be unique

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#65]
```
As a visitor
When I visit the user registration page
If I fill out the registration form
But include an email address already in the system
Then I am returned to the registration page
My details are not saved and I am not logged in
The form is filled in with all previous data except the email field and password fields
I see a flash message telling me the email address is already in use
```

DO THESE STORIES FIRST:
- User Story 2, User Registration

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #68

child of #70

depends on #67

**Comment by MackHalliday** [comment]
Final check OK
