### ISSUE TITLE
User Story 3, User Registration Missing Details

### ISSUE THREAD

**Issue by BrianZanti** [leiyakenney/monster_shop_1906#66]
```
As a visitor
When I visit the user registration page
And I do not fill in this form completely,
I am returned to the registration page
And I see a flash message indicating that I am missing required fields
```

DO THESE STORIES FIRST:
- User Story 2, User Registration

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #68

child of #70

depends on #67

**Comment by MackHalliday** [comment]
Final check OK
